---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos7
    provisioner:
      require_chef_omnibus: 12
    driver_config:
      box: centos/7
      box_url: https://atlas.hashicorp.com/centos/boxes/7/versions/1602.02/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[chef_example::include_before]
      - role[app_three]
      - role[app_plusplus]
    attributes:
